openapi: 3.1.0
x-stoplight:
  id: pmh5351fgxnhc
info:
  title: serp
  version: '1.0'
  summary: google serp
servers:
  - url: 'http://localhost:3000'
    variables:
      var1:
        default: get-serp
        description: ''
paths:
  /v1/scrape:
    parameters: []
    get:
      summary: Get SERP
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-serp
      description: Retrieve the information from Google SERP page.
      x-stoplight:
        id: jc0y71h9p1dq5
      parameters:
        - schema:
            type: string
            default: hello
          in: query
          name: q
          required: true
        - schema:
            type: string
            default: en
          in: query
          name: hl
          required: true
        - schema:
            type: string
            default: us
          in: query
          name: gl
          required: true
        - schema:
            type: string
            default: playwright-render-page
          in: query
          name: scrape_method
          required: true
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: e31f4wobk2tfx
        firstName:
          type: string
          x-stoplight:
            id: 4t44q42a5qvaq
        lastName:
          type: string
          x-stoplight:
            id: x5r8j9mt7mb7j
        email:
          type: string
          format: email
          x-stoplight:
            id: c0jnd0q46nv09
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: b4v61bbgoyivt
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: hry60l8llmi86
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: jos95zj64u6wy
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: 8nigc93guozog
